data_cfg:
  csv_path: metadata/rna_metadata.csv
  filtering:
    max_len: 150
    min_len: 40
  min_t: 0.01
  samples_per_eval_length: 5
  num_eval_lengths: 10
  batch_size: 28
  max_batch_size: 28
  max_squared_res: 19000
  max_num_res_squared: 19000
  eval_batch_size: 5
  num_workers: 4
  prefetch_factor: 100
  linear_effect: true
interpolant:
  min_t: 0.01
  rots:
    train_schedule: linear
    sample_schedule: exp
    exp_rate: 10
  trans:
    train_schedule: linear
    sample_schedule: linear
  sampling:
    num_timesteps: 50
  self_condition: ${model.edge_features.self_condition}
model:
  use_flashipa: true
  mode: flash_1d_bias
  node_embed_size: 256
  edge_embed_size: 128
  symmetric: false
  node_features:
    c_s: ${model.node_embed_size}
    c_pos_emb: 128
    c_timestep_emb: 128
    embed_diffuse_mask: false
    max_num_res: 2000
    timestep_int: 1000
  edge_features:
    mode: ${model.mode}
    max_len: ${data_cfg.filtering.max_len}
    z_factor_rank: 2
    single_bias_transition_n: 2
    c_s: ${model.node_embed_size}
    c_p: ${model.edge_embed_size}
    relpos_k: 64
    use_rbf: true
    num_rbf: 32
    feat_dim: 64
    num_bins: 22
    self_condition: true
    k: 20
  ipa:
    use_flash_attn: true
    attn_dtype: bf16
    use_packed: true
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 128
    no_heads: 8
    z_factor_rank: ${model.edge_features.z_factor_rank}
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 6
experiment:
  debug: false
  seed: 123
  num_devices: 1
  warm_start: null
  warm_start_cfg_override: true
  use_swa: false
  batch_ot:
    enabled: true
    cost: kabsch
    noise_per_sample: 1
    permute: false
  training:
    min_plddt_mask: null
    loss: se3_vf_loss
    bb_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0
    aux_loss_weight: 1.0
    aux_loss_t_pass: 0.25
    tors_loss_scale: 1.0
    num_non_frame_atoms: 0
  wandb:
    name: rna-frameflow
    project: se3-fm
    save_code: false
    tags: []
    mode: online
  optimizer:
    lr: 0.0001
  trainer:
    overfit_batches: 0
    max_time: 00:20:00:00
    min_epochs: 1
    max_epochs: 200
    accelerator: gpu
    log_every_n_steps: 10
    deterministic: false
    strategy: ddp_find_unused_parameters_true
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 1
  checkpointer:
    dirpath: ./
    save_last: true
    save_top_k: 3
    monitor: train/loss
    mode: min
    every_n_epochs: 40
inference:
  run_inference: true
  seed: 123
  ckpt_path: camera_ready_ckpts/rna_frameflow_public_weights.ckpt
  output_dir: generated_rna_bb_samples
  name: flattened_samples
  evalsuite:
    run_eval: false
    eval_save_dir: evalsuite_metrics_rmsd
    paths:
      rnasolo_path: data/rnasolo/
      rnasolo_metadata_path: metadata/rna_metadata.csv
      usalign_path: rna_backbone_design/tools/cpp/USalign
      qtmclust_path: rna_backbone_design/tools/cpp/qTMclust
      tmscore_path: rna_backbone_design/tools/cpp/TMscore
    constants:
      seqlen_range:
      - 40
      - 150
      tm_thresh: 0.45
      rmsd_thresh: 5.5
  use_gpu: true
  num_gpus: 1
  interpolant:
    min_t: 0.01
    rots:
      corrupt: true
      sample_schedule: exp
      exp_rate: 10
    trans:
      corrupt: true
      sample_schedule: linear
    sampling:
      num_timesteps: 50
    self_condition: true
  samples:
    samples_per_length: 50
    min_length: 40
    max_length: 150
    length_step: 10
    length_subset: null
    overwrite: false
